server:
  port: 0.0.0.0:9044

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/task?charset=utf8&parseTime=True&loc=Asia%2FShanghai"

gorm:
  printSql: true

task:
  home: D:\csion.project\Go\code\taskHome\
  worker:
    MNode: 192.168.13.1:9044
    Auth: 6b715129f1a3449ebad0ec0ef0ab1bc